apiVersion: v1
kind: Service
metadata:
  name: piraeus-etcd-dns
  namespace: kube-system
  labels:
    app.kubernetes.io/name: piraeus
    app.kubernetes.io/component: piraeus-etcd-dns
spec:
  ports:
  - name: client
    port: 2379
  - name: peer
    port: 2380
  clusterIP: None
  selector:
    app.kubernetes.io/name: piraeus
    app.kubernetes.io/component: piraeus-etcd-dns
---
apiVersion: v1
kind: Service
metadata:
  name: piraeus-etcd
  namespace: kube-system
  labels:
    app.kubernetes.io/name: piraeus
    app.kubernetes.io/component: piraeus-etcd
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
  - name: client
    port: 2379
    targetPort: 2379
  - name: peer
    port: 2380
    targetPort: 2380
  selector:
    app.kubernetes.io/name: piraeus
    app.kubernetes.io/component: piraeus-etcd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: piraeus-etcd
  namespace: kube-system
  labels:
    app.kubernetes.io/name: piraeus
    app.kubernetes.io/component: piraeus-etcd
spec:
  serviceName: piraeus-etcd
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: piraeus
      app.kubernetes.io/component: piraeus-etcd
  replicas: 3
  template:
    metadata:
      name: piraeus-etcd
      labels:
        app.kubernetes.io/name: piraeus
        app.kubernetes.io/component: piraeus-etcd
    spec:
      priorityClassName: system-node-critical
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      initContainers:
      - name: init
        image: quay.io/piraeusdatastore/piraeus-init:v0.5.1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: CLUSTER_SIZE
          value: "3"
        - name: THIS_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: THIS_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: init
          mountPath: /init
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.4.3
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
        ports:
        - name: client
          containerPort: 2379
        - name: peer
          containerPort: 2380
        command:
        - etcd
        args:
        - --config-file
        - /etc/etcd/etcd.conf
        readinessProbe:
          successThreshold: 3
          failureThreshold: 3
          httpGet:
            path: /health
            port: 2379
          initialDelaySeconds: 10
          periodSeconds: 1
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: init
          mountPath: /etc/etcd
          subPath: etc/etcd
        - name: data
          mountPath: /.etcd/data
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: init
        emptyDir: {}
      - name: data
        emptyDir: {}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                - piraeus-etcd
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      tolerations:
      - operator: Exists
        effect: NoSchedule
