apiVersion: v1
kind: Service
metadata:
  name: piraeus-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: piraeus
    app.kubernetes.io/component: piraeus-controller
spec:
  type: ClusterIP
  ports:
  - port: 3370
    name: rest-api
    targetPort: 3370
  selector:
    app.kubernetes.io/name: piraeus
    app.kubernetes.io/component: piraeus-controller
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: piraeus-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: piraeus
    app.kubernetes.io/component: piraeus-controller
spec:
  serviceName: piraeus-controller
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: piraeus
      app.kubernetes.io/component: piraeus-controller
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: piraeus
        app.kubernetes.io/component: piraeus-controller
    spec:
      priorityClassName: system-node-critical
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
      dnsPolicy: ClusterFirst
      initContainers:
      - name: init
        image: quay.io/piraeusdatastore/piraeus-init:v0.2
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: THIS_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ETCDCTL_ENDPOINTS
          value: http://piraeus-etcd:2379
        - name: ETCDCTL_API
          value: "3"
        - name: ETCD_CLUSTER_SIZE
          value: "3"
        - name: TIMEOUT
          value: "3600"
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: etc-linstor
          mountPath: /etc/linstor
      containers:
      - name: controller
        image: quay.io/piraeusdatastore/piraeus-server:v1.3.1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
        ports:
        - name: rest-api
          containerPort: 3370
          hostPort: 3370
        - name: plain
          containerPort: 3376
          hostPort: 3376
        - name: ssl
          containerPort: 3377
          hostPort: 3377
        args:
        - startController
        readinessProbe:
          successThreshold: 3
          failureThreshold: 3
          httpGet:
            port: 3370
          initialDelaySeconds: 5
          periodSeconds: 1
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: etc-linstor
          mountPath: /etc/linstor
        - name: log
          mountPath: /var/log/linstor-controller
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: etc-linstor
        emptyDir: {}
      - name: log
        hostPath:
          path: /var/log/piraeus/linstor-controller
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      tolerations:
      - operator: Exists
        effect: NoSchedule
