apiVersion: v1
kind: ConfigMap
metadata:
  name: piraeus-controller
  namespace: piraeus-system
data:
  INIT_DEBUG: "false"
  ETCD_ENDPOINTS: piraeus-etcd.piraeus-system.svc.cluster.local:2379
  LS_CONTROLLERS: piraeus-controller.piraeus-system.svc.cluster.local:3370
---
apiVersion: v1
kind: Service
metadata:
  name: piraeus-controller
  namespace: piraeus-system
  labels:
    app.kubernetes.io/name: piraeus
    app.kubernetes.io/component: piraeus-controller
spec:
  type: ClusterIP
  ports:
  - port: 3370
    name: rest-api
    targetPort: 3370
  selector:
    app.kubernetes.io/name: piraeus
    app.kubernetes.io/component: piraeus-controller
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: piraeus-controller
  namespace: piraeus-system
  labels:
    app.kubernetes.io/name: piraeus
    app.kubernetes.io/component: piraeus-controller
spec:
  serviceName: piraeus-controller
  updateStrategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: piraeus
      app.kubernetes.io/component: piraeus-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: piraeus
        app.kubernetes.io/component: piraeus-controller
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
      dnsPolicy: ClusterFirst
      initContainers:
      - name: init
        image: quay.io/piraeusdatastore/piraeus-init:v0.5.6
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        envFrom:
        - configMapRef:
            name: piraeus-controller
        args:
        - initController
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - name: init
          mountPath: /init
      containers:
      - name: controller
        image: quay.io/piraeusdatastore/piraeus-server:v1.4.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
        ports:
        - name: rest-api
          containerPort: 3370
          hostPort: 3370
        - name: plain
          containerPort: 3376
          hostPort: 3376
        - name: ssl
          containerPort: 3377
          hostPort: 3377
        env:
        - name: THIS_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - startController
        readinessProbe:
          httpGet:
            port: 3370
          successThreshold: 3
          failureThreshold: 3
          periodSeconds: 5
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - name: init
          mountPath: /etc/linstor
          subPath: etc/linstor
        - name: log
          mountPath: /var/log/linstor-controller
      volumes:
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/Etc/UTC
      - name: init
        emptyDir: {}
      - name: log
        hostPath:
          path: /var/log/piraeus/linstor-controller
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - key: CriticalAddonsOnly
        operator: Exists
