#@data/values
---
name: "piraeus"
map_host_linstor: false
map_host_lvm: false
registry: "quay.io/piraeusdatastore"
initversion: "v0.2"
contsatversion: "v1.3.1"
csiversion: "v0.7.2"
images:
  init: "piraeus-init"
  controller: "piraeus-server"
  satellite: "piraeus-server"
  csi: "piraeus-csi"
