#@data/values
---
name: "piraeus"
namespace: "piraeus-system"
timezone: "/usr/share/zoneinfo/Etc/UTC"
map_host_linstor: true
map_host_lvm: false
set_priority_class: false
registry: "quay.io/piraeusdatastore"
etcdversion: "v3.4.7"
initversion: "v0.5.6"
contsatversion: "v1.4.2"
csiversion: "v0.7.4"
clientversion: "latest"
images:
  init: "piraeus-init"
  controller: "piraeus-server"
  satellite: "piraeus-server"
  csi: "piraeus-csi"
  client: "piraeus-client"