name: Build DRDB v9.2.3 RC1 Ubuntu Image
on:
  push:
    branches:
      - 9.2.3*
jobs:
  build-greenplum-image:
    name: DRDB v9.2.3 RC1 Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Create tag
        id: docker_tag
        run: |
          commit_tag=${GITHUB_REF#refs/*/}
          echo "tag=${commit_tag}-${{ github.run_number }}" >> $GITHUB_OUTPUT
      - name: Verify tag
        run: echo ${{ steps.docker_tag.outputs.tag }}
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }} 
      - name: Build and push
        # docker build -t gcr.io/plaidcloud-build/auth-service:latest --pull --build-arg PLAID_BUILD_TAG={tag} --no-cache .
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          pull: true
          no-cache: true
          file: dockerfiles/Dockerfile.jammy
          build-args: |
            PLAID_BUILD_TAG=${{ steps.docker_tag.outputs.tag }}
          tags: gcr.io/plaidcloud-build/drdb:latest,gcr.io/plaidcloud-build/drdb-oss:${{ github.ref_name }}-${{ github.run_number }}
